import Head from "next/head";
import HeroCard from "../components/common/HeroCard";
import Banner from "../components/Home/Banner";
import Explore from "../components/Home/Explore";
import Places from "../components/Home/Places";
import { exploreNearbyData, fetchAccomodationPlaces } from "../services";

type Props = {
  exploreData?: IExploreData[];
  accomodationPlaces?: IPlaces[];
};

export default function Home({ exploreData, accomodationPlaces }: Props) {
  return (
    <>
      <Head>
        <title> Reserve Stay on the go! </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://a0.muscache.com/airbnb/static/icons/android-icon-192x192-c0465f9f0380893768972a31a614b670.png"
        />
      </Head>

      <Banner />
      <main className="mx-auto max-w-7xl px-8 sm:px-16">
        <Explore exploreData={exploreData} />
        <Places places={accomodationPlaces} />

        <HeroCard
          img="https://links.papareact.com/4cj"
          title="The Greatest Outdoors"
          description="Wishlists by Airbnb"
          buttonText="Get Inspired"
        />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const exploreData = await exploreNearbyData();
  const accomodationPlaces = await fetchAccomodationPlaces();
  return {
    props: {
      exploreData: exploreData || null,
      accomodationPlaces: accomodationPlaces || null,
    },
  };
}
