import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title> Reserve Stay on the go! </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://a0.muscache.com/airbnb/static/icons/android-icon-192x192-c0465f9f0380893768972a31a614b670.png"
        />
      </Head>
      <main></main>
    </>
  );
}
